name: symp_ai

services:
  api:
    container_name: fast-api
  
    build:
      dockerfile: ./api/Dockerfile

    ports:
      - 3069:3069
    
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/symp_ai

    depends_on:
      db:
        condition: service_healthy
      db-seed:
        condition: service_completed_successfully
  

  db:
    image: postgres:17.9

    environment:
      POSTGRES_DB: symp_ai
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d symp_ai"]
      interval: 5s
      timeout: 3s
      retries: 10

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  db-seed:
    image: postgres:17.9
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./db/mock_data.sql:/seed/mock_data.sql:ro
    command: ["sh", "-c", "psql -h db -U postgres -d symp_ai -f /seed/mock_data.sql"]
    restart: "no"

  tlg:
    container_name: sympai-tlg
    build:
      dockerfile: Dockerfile
      context: ./tlg
    environment:
      TOKEN: ${TELEGRAM_TOKEN}
      API_URL: http://api:3069
    depends_on:
      - api

  web:
    container_name: sympai-web
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "3000:3000"
    environment:
      API_URL: http://api:3069
    depends_on:
      - api
